#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-checkstyle-plugin
Version  : 2.17
Release  : 1
URL      : https://github.com/apache/maven-checkstyle-plugin/archive/maven-checkstyle-plugin-2.17.tar.gz
Source0  : https://github.com/apache/maven-checkstyle-plugin/archive/maven-checkstyle-plugin-2.17.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.17/maven-checkstyle-plugin-2.17.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.17/maven-checkstyle-plugin-2.17.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
A real tab

%prep

%build

%install

%files
%defattr(-,root,root,-)
